---
title: "Data Processing"
author: ""
date: '(`r format(Sys.time(), "%B %d, %Y")`)'
output: 
  github_document: default
  html_notebook: default 
---

## Introduction
This notebook...

## Dependencies
This notebook requires a number of `R` packages:

```{r load-packages}
# tidyverse packages
library(dplyr)        # data wrangling

# other packages
library(here)         # file path management
```

## Load Data
This notebook requires the following raw data:

```{r load-data}
load(here("data", "raw", "prcl_db.rda"))
```

## Process Parcel Data

```{r}
prcl_BldgCom <- select(prcl_db$BldgCom, Parcel, BldgCategory, BldgType, 
                              GroundFloorArea, ComExtWallType,ComStoriesCode, 
                              YearBuilt, ComConstType, TotApts, NbrOfAptsEff, 
                              NbrOfApts1Br, NbrOfApts2Br, NbrOfApts3Br, 
                              NbrOfAptsOther)
prcl_BldgRes <- select(prcl_db$BldgRes, Parcel, ResOccType, BsmtType, BsmtFinishType, BsmtAreaFinished, ResExtWallType, LivingAreaTotal, LivingAReaAtGrade, LivingAreaUpDown, FullBaths, HalfBaths, AirCondCentral, AirCondWindow, CentralHeating, Attic, Garage1, Garage2, Carport1, Carport2, YearBuilt, ResModelCode, ResModelAdjCode)

prcl_Prcl <- select(prcl_db$Prcl, Handle, AsrClassCode, AsrLandUse1, AsrLandUse2, Condominium, NbrOfUnits, NbrOfApts,Frontage, LandArea, AsdLand, AsdImprove, BillLand, BillImprove, AprLand, CostAprImprove, PriorAsdLand, PriorAsdImprove, PriorTaxAmt, CDALandUse1, CDLandUse2, Zoning, NbrOfBldgsRes, NbrOfBldgsCom, ResSalePrice, ResSaleDate)

prcl_prclREAR <- select(prcl_db$PrclREAR, Parcel, LastUpdate, TaxBal, ComResCode, NbrOfSewerLines, SewerLineSplit)
```

